---
# handlers file for role_lx_install_elk

- name: Restart elasticsearch
  service: name=elasticsearch enabled=yes state=restarted

- name: Restart kibana
  service: name=kibana enabled=yes state=restarted

- name: Restart Nginx
  service: name=nginx enabled=yes state=restarted
